name: bitcoin_ticker
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  cupertino_icons: ^0.1.2
  flutter:
    sdk: flutter
  http: ^0.13.5

dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
