name: bmi_calculator
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.3
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.3.0

dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
