name: flash_chat
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  animated_text_kit: ^4.2.2
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.3
  firebase_auth: ^4.2.5
  firebase_core: ^2.4.1
  flutter:
    sdk: flutter
  modal_progress_hud_nsn: ^0.3.0

dev_dependencies:
  blackfoot_flutter_lint: ^1.0.6
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - images/
